config/routes.rb
Rails.application.routes.draw do

	root'books#top'
	get '/home/about', to: 'books#about'
  get '/search', to: 'search#search'
  devise_for :users
  resources :books, only:[:new, :create, :index, :show, :destroy,:edit,:update] do
	  resource :favorites, only: [:create, :destroy]
	  resource :book_comments, only: [:create, :destroy]
  end
  resources :relationships, only: [:index, :create, :destroy]
  resources :users, only:[:new,:index,:show, :update, :edit] do
  	 member do
     get :followings, :followers
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  attachment :profile_image

  has_many :books
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  validates :name, length: {in: 2..20}
  validates :introduction, length: {maximum: 50}

  # 能動的関係
  has_many :relationships, dependent: :destroy
  has_many :followings, through: :relationships, source: :follow
  # 受動的関係
  has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'follow_id', dependent: :destroy
  has_many :followers, through: :reverse_of_relationships, source: :user

  def follow(other_user)
    unless self == other_user
      self.relationships.find_or_create_by(follow_id: other_user.id)
    end
  end

  def unfollow(other_user)
    relationship = self.relationships.find_by(follow_id: other_user.id)
    relationship.destroy if relationship
  end

  def following?(other_user)
    self.followings.include?(other_user)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  # before_action :ensure_correct_user(params[:id]), {only: [:edit, :update, :destroy]}

  def show
  	@user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
  end

  def create
      @book.user_id = current_user.id
      @book = Book.new(book_params)
   if @book.save
   flash[:success] = "You have creatad user successfully."
      redirect_to @book
    else
   flash[:danger] = @book.errors.full_messages
      @books = Book.all
      render 'index'
    end
  end

  def index
    @users = User.all
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
    if current_user.id != @user.id
      redirect_to user_path(current_user)
    end
  end

  def update
    if current_user
       @user = User.find(params[:id])
       if @user.update(user_params)
       	flash[:success] = "You have updated user successfully."
          redirect_to user_path(@user.id)
         else
          flash[:danger] = @user.errors.full_messages
          render "edit"
       end
     else
    end
   end

  def followings
    @user = User.find(params[:id])
    @users = @user.followings
    render 'show_follow'
  end

  def followers
    @user = User.find(params[:id])
    @users = @user.followers
    render 'show_follower'
  end

  private
  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_index.html.erb
<table class='table'>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% users.each do |user| %>
      <tr>
        <td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no_image.jpg") %></td>
        <td><%= user.name %></td>
        <td><%= link_to 'Show', user, class: "user_#{user.id}" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_info.html.erb
    <h1>User Info</h1>
      <div>
        <%= attachment_image_tag user, :profile_image, :fill, 100, 100, format:'jpeg', class: "pull-left profile-img", fallback: "no_image.jpg" %>
      </div>
      <table class="table">
        <tbody>
          <tr>
            <th>name</th>
            <th><%= user.name %></th>
         </tr>
          <tr>
            <th>introduction</th>
            <th><%= user.introduction %></th>
          </tr>
                    <tr>
            <th>フォローしている</th>
            <th><%= link_to "#{user.followings.count} フォロー", followings_user_path(user) %></th>
          </tr>
                    <tr>
            <th>フォローされている</th>
            <th><%= link_to "#{user.followers.count} フォロー", followers_user_path(user) %></th>
          </tr>
        </tbody>
      </table>

      <% if user == current_user %>
     <%= link_to '',edit_user_path(current_user.id),class: "btn btn-block btn-default glyphicon glyphicon-wrench edit_user_#{current_user.id}" %>
     <% end %>

app/views/users/edit.html.erb
<h1>Users info</h1>
<%= form_for @user do |f| %>


                          <% if @user.errors.any? %>
                          <%= @user.errors.count %>errors
                                  <ul>
                                  <% @user.errors.full_messages.each do |message| %>
                                    <li><%= message %></li>
                                  <% end %>
                                  </ul>
                                <% end %>


    <div class="form-group">
      <%= f.label :name %><br>
      <%= f.text_field :name, autofocus: true ,class: "form-control name"%>
    </div>

    <div class="form-group">
      <%= f.label :image %><br />
      <%= f.attachment_field :profile_image,class: "user_image" %>
    </div>

    <div class="form-group">
      <%= f.label :introduction %><br />
      <%= f.text_area :introduction, autofocus: true ,class: "form-control introduction"%>
    </div>


    <div class="actions">
    <%= f.submit "Update User", class: "btn btn-primary" %>
    </div>
<% end %>

app/views/users/index.html.erb
<div class="container">

<div class="row">
  <div class="col-md-4">
    <%= render 'info',{user:current_user} %>

    <%= render 'books/side',{book:@book, user:current_user} %>
  </div>


  <div class="col-md-8">
      <table class="table">
        <h1>Users</h1>
          <thead>
            <tr>
              <th>Image</th>
              <th>name</th>
            </tr>
          </thead>

          <% @users.each do |user| %>
          <tbody>
            <tr>
              <td>
                 <div><%= attachment_image_tag user, :profile_image, :fill, 50, 50, format:'jpeg', class: "pull-left profile-img", fallback: "no_image.jpg" %></div>
              </td>
              <td>
                <%= user.name %>
              </td>
              <td>
                <%= link_to "show",user_path(user.id), class: "user_#{user.id}" %>
              </td>
            </tr>
          </tbody>
          <% end %>
      </table>

  </div>
</div>
</div>

app/views/users/show.html.erb
<div class="container">
<div class="row">
  <div class="col-md-4">

    <%= render 'info',{user: @user} %>
    <%= render 'relationships/follow_button', user: @user %>
    <%= render 'books/side',{book:@book, user:current_user} %>
  </div>

  <div class="col-md-8">
      <table class="table">
        <h1>Books</h1>
          <thead>
            <tr>
              <th></th>
              <th>Title</th>
              <th>Opinion</th>
            </tr>
          </thead>

            <% @books.each do |book| %>
                <tbody>
                  <tr>
                    <td>
                      <%= attachment_image_tag book.user, :profile_image, :fill, 50, 50, format:'jpeg', class: "pull-left profile-img", fallback: "no_image.jpg" %>
                    </td>
                    <td>
                <%=link_to book.title, book, class: "book_#{book.id}" %>
                    </td>
                    <td>
                      <%= book.body %>
                    </td>
              
              <td>
                <!-- ここからいいね機能 -->
                <% if book.favorited_by?(current_user) %>
                    <%= link_to book_favorites_path(book), method: :delete do %>
                      <i><span class="glyphicon glyphicon-heart" aria-hidden="true"></span></i>
                      <%= book.favorites.count %>
                    <% end %>

                <% else %>
                    <%= link_to book_favorites_path(book), method: :post do %>
                      <i><span class="glyphicon glyphicon-heart-empty" aria-hidden="true"></span></i>
                      <%= book.favorites.count %>
                    <% end %>
                <% end %>
                <!-- ここまで -->
              </td>
                            <!-- ここからコメント -->
                <td>
                  <%= link_to "#{book.book_comments.count} コメント", book_path(book.id) %>
                </td>
              <!-- ここまで -->

                   <% end %>
                  </tr>
                </tbody>

      </table>
  </div>
</div>

app/views/users/show_follow.html.erb
<div class="container">
    <h2>Followings</h2>
    <p><%= @user.name %>がフォローしているユーザー</p>

      <table class="table table-striped">
           <thead>
		      <tr>
		        <th>image</th>
		        <th>name</th>
		        <th></th>
		        <th></th>
		      </tr>
           </thead>

           <% @user.followings.each do |user| %>
           <tbody>
            <tr>
              <td>
                 <div><%= attachment_image_tag user, :profile_image, :fill, 50, 50, format:'jpeg', class: "pull-left profile-img", fallback: "no_image.jpg" %></div>
              </td>
              <td>
                <%= user.name %>
              </td>
              <td>
                <%= link_to "show",user_path(user.id), class: "user_#{user.id}" %>
              </td>
              <td>
 				 <%= render 'relationships/follow_button', user: user %>
               </td>
            </tr>
           </tbody>
<% end %>
</table>
</div>

app/views/users/show_follower.html.erb
<div class="container">
    <h2>Followers</h2>
    <p><%= @user.name %>がフォローされているユーザー</p>

        <table class="table table-striped">
        	          <thead>
      <tr>
        <th>image</th>
        <th>name</th>
        <th></th>
        <th></th>
      </tr>
                </thead>

              <% @user.followers.each do |user| %>
              <tbody>
            <tr>
              <td>
                 <div><%= attachment_image_tag user, :profile_image, :fill, 50, 50, format:'jpeg', class: "pull-left profile-img", fallback: "no_image.jpg" %></div>
              </td>
              <td>
                <%= user.name %>
              </td>
              <td>
                <%= link_to "show",user_path(user.id), class: "user_#{user.id}" %>
              </td>
            </tr>
        </tbody>
<% end %>
</table>
</div>