config/routes.rb
Rails.application.routes.draw do

	root'books#top'
	get '/home/about', to: 'books#about'
  get '/search', to: 'search#search'
  devise_for :users
  resources :books, only:[:new, :create, :index, :show, :destroy,:edit,:update] do
	  resource :favorites, only: [:create, :destroy]
	  resource :book_comments, only: [:create, :destroy]
  end
  resources :relationships, only: [:index, :create, :destroy]
  resources :users, only:[:new,:index,:show, :update, :edit] do
  	 member do
     get :followings, :followers
    end
  end
end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user
    has_many :favorites, dependent: :destroy
    def favorited_by?(user)
      favorites.where(user_id: user.id).exists?
    end
	has_many :book_comments, dependent: :destroy
	validates :title, presence: true
	validates :body, presence: true, length: {maximum: 200}
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
   before_action :authenticate_user!, except:[:top, :about]

  def index
    @books = Book.all
    @book = Book.new
  end

  def show
    @book = Book.find(params[:id])
    @user = @book.user
    @post = Book.new
    @book_comment = BookComment.new

  end

  def top
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id

   if @book.save
      flash[:success] = "successfully"
      redirect_to @book
    else
      flash[:danger] = @book.errors.full_messages
      @books = Book.all
      render 'index'
    end
  end


  def edit
    @book = Book.find(params[:id])
    if current_user.id != @book.user_id
      redirect_to books_path
    end
  end

  def about
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
    flash[:success] = "successfully"
    redirect_to @book
    else
      flash[:danger] = @book.errors.full_messages
      render "edit"
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private
  def book_params
    params.require(:book).permit(:title,:body)

  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_index.html.erb
<table class='table table-hover table-inverse'>
  <thead>
    <tr> 
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% books.each do |book| %>
      <tr>
        <td><%= link_to(book.user) do %>
          <%= attachment_image_tag(book.user, :profile_image, :fill, 50, 50, fallback: "no_image.jpg") %>
          <% end %>
        </td>
        <td><%= link_to book.title,book, class: "book_#{book.id}" %></td>
        <td><%= book.body %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/books/_side.html.erb
                 <h1>New book</h1>
                   <%= form_for(book, url: books_path)do |f| %>
                          <% if @book.errors.any? %>
                          <%= @book.errors.count %>errors
                                  <ul>
                                  <% @book.errors.full_messages.each do |message| %>
                                    <li><%= message %></li>
                                  <% end %>
                                  </ul>
                                <% end %>
                     <%= f.label :title %>
                     <%= f.text_field :title, class: "form-control book_title"%>
                     <%= f.label :opinion %>
                     <%= f.text_area :body, class: "form-control book_body" %>
                     <%= f.submit class: "btn btn-block btn-primary" %>
                   <% end %>

app/views/books/about.html.erb
<h2>welcome to<span class="glyphicon glyphicon-book" aria-hidden="true"></span><strong>Bookers  !!</strong></h2>

app/views/books/edit.html.erb
<div class="container">
<div class="row">
  <div class="col-md-8 col-md-offset-2">

<h2>Editing Book</h2>

<%= form_for @book do |f| %>

                          <% if @book.errors.any? %>
                            <%= @book.errors.count %>errors
                            <ul>
                             <% @book.errors.full_messages.each do |message| %>
                               <li><%= message %></li>
                             <% end %>
                             </ul>
                     <% end %>



    <div class="form-group">
      <%= f.label :title %><br>
      <%= f.text_field :title, autofocus: true ,class: "form-control book_title"%>
    </div>

    <div class="form-group">
      <%= f.label :opinion %><br />
      <%= f.text_area :body, autofocus: true ,class: "form-control book_body"%>
    </div>



    <div class="actions">
    <%= f.submit "Update book", class: "btn btn-primary" %>
    </div>
<% end %>


</div>
</div>
</div>

app/views/books/index.html.erb
<div class="container">
<div class="row">
  <div class="col-md-4">
    <%= render 'users/info',{user:current_user} %>

    <%= render 'side',{book:@book, user:current_user} %>
  </div>

  <div class="col-md-8">
      <table class="table">
        <h1>Books</h1>

          <thead>
            <tr>
              <th></th>
              <th>Title</th>
              <th>Opinion</th>
              <th></th>
              <th></th>
            </tr>
          </thead>

          <% @books.each do |book| %>
          <tbody>
            <tr>
              <td>
                <%= attachment_image_tag book.user, :profile_image, :fill, 50, 50, format:'jpeg', class: "pull-left profile-img", fallback: "no_image.jpg" %>
              </td>
              <td>
                <%=link_to book.title, book_path(book), class: "book_#{book.id}" %>
              </td>
              <td>
                <%= book.body %>
              </td>
              <td>
                <!-- ここからいいね機能 -->
                <% if book.favorited_by?(current_user) %>
                    <%= link_to book_favorites_path(book), method: :delete do %>
                      <i><span class="glyphicon glyphicon-heart" aria-hidden="true"></span></i>
                      <%= book.favorites.count %> いいね
                    <% end %>

                <% else %>
                    <%= link_to book_favorites_path(book), method: :post do %>
                      <i><span class="glyphicon glyphicon-heart-empty" aria-hidden="true"></span></i>
                      <%= book.favorites.count %> いいね
                    <% end %>
                <% end %>
                <!-- ここまで -->
              </td>
              <!-- ここからコメント -->
                <td>
                  <%= link_to "#{book.book_comments.count} コメント", book_path(book.id) %>
                </td>
              <!-- ここまで -->

    <% end %>
  </tr>
</tbody>

      </table>

  </div>
</div>
</div>

app/views/books/show.html.erb
<div class="container">
<div class="row">
  <div class="col-md-4">
    <%= render 'users/info',{user:@book.user} %>
    <%= render 'relationships/follow_button', user: @user %>
    <%= render 'side',{book:@post, user:@book.user} %>
  </div>

  <div class="col-md-8">

    <table class="table">
    <h1>Book detail</h1>

    <thead>
      <tr>
        <th></th>
        <th>Title</th>
        <th>Opinion</th>
        <th></th>
      </tr>
    </thead>
          <tr>
        <th>
          <%= attachment_image_tag @book.user, :profile_image, :fill, 50, 50, format:'jpeg', class: "pull-left profile-img", fallback: "no_image.jpg" %>

           <%= link_to @user.name ,user_path(@user.id) %>


        </th>
        <th><%= @book.title %></th>
        <th><%= @book.body %></th>

                <!-- ここからいいね機能 -->
                <% if @book.favorited_by?(current_user) %>
                  <th>
                    <%= link_to book_favorites_path(@book), method: :delete do %>
                      <i><span class="glyphicon glyphicon-heart" aria-hidden="true"></span></i>
                      <%= @book.favorites.count %> いいね</th>
                    <% end %>
                <% else %>
                  <th>
                    <%= link_to book_favorites_path(@book), method: :post do %>
                      <i><span class="glyphicon glyphicon-heart-empty" aria-hidden="true"></span></i>
                      <%= @book.favorites.count %> いいね
                    <% end %>
                  </th>
                <% end %>

                    <% if @book.user == current_user %>
                      <td>
                         <button type="button" class="btn btn-info"><%= link_to "edit",edit_book_path, class: "edit_book_#{@book.id}" %></button>
                      </td>
                      <td>
                       <button type="button" class="btn btn-danger"><%= link_to "Destroy",book_path,method: :delete, class: "destroy_book_#{@book.id}" %></button>
                      </td>
                      <% end %>
                <!-- ここまで -->
      </tr>
        </table>
                <!-- ここからコメント -->

                  <div class="comment-list bt style-2" id="comments">
                    <div class="float-wrapper">
                        <h3 class="comment-count"><%= @book.book_comments.count %>件コメント</h3>
                    </div>
                    <ol>
                      <% @book.book_comments.each do |book_comment| %>
                          <li class="comment">
                              <div class="comment-body bb">
                                  <div class="comment-text">
                                      <div class="comment-author clearfix">
                                          <a href="#" class="link-author"><%= book_comment.user.name %></a>
                                          <span class="comment-meta">
                                            <span class="comment-date"><%= book_comment.created_at.strftime('%Y/%m/%d') %></span>
                                          </span>
                                      </div>
                                      <div class="comment-entry"><%= book_comment.comment %></div>
                                  </div>
                              </div>
                                                <!-- コメント削除 -->
                  <% if book_comment.user == current_user %>
                   <%= link_to "削除", book_book_comments_path(book_comment), method: :delete, class: "btn btn-danger" %>
                  <% end %>
                                                  <!-- ここまで-->
                          </li>
                      <% end %>
                  </ol>

                  <%= form_for [@book, @book_comment] do |f| %>
                    <div class="row">
                        <div class="col-sm-12">
                            <%= f.text_area :comment, rows:'5', class: "form-control",placeholder: "コメントをここに" %>
                        </div>
                    </div>
                    <%= f.submit "送信する", class: "btn btn-lg btn-base-1 mt-20 pull-right" %>
                  <% end %>
                                      <% if @book_comment.user == current_user %>
                      <td>
                       <button type="button" class="btn btn-danger"><%= link_to "削除", book_book_comment_path(@book, book_comment), method: :delete, remote: true, class: "btn btn-danger" %></button>
                      </td>
                      <% end %>
                <!-- ここまで -->

  </div>
</div>
</div>

app/views/books/top.html.erb
<div class="container">
  <div class="row">
    <div class="main col-md-offset-3 col-md-6">


      <h2>welcome to<span class="glyphicon glyphicon-book" aria-hidden="true"></span><strong>Bookers  !!</strong></h2>
      <p>In <span class="glyphicon glyphicon-book" aria-hidden="true"></span><strong>Bookers,</strong><br>you can share and exchange your opinions , inpressions , and emotions<br>about various books!</p>

       <%= link_to "Log in",new_user_session_path, class: "sign_in btn btn-info col-xs-10 col-xs-offset-1" %>
      <%= link_to "Sign up",new_user_registration_path, class: "sign_up btn btn-success col-xs-10 col-xs-offset-1" %>
       </div>
    </div>
  </div>